local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp", "storage") %>

cloudflare:
  service: S3
  access_key_id: <%= Rails.application.env_credentials.cloudflare.r2.access_key_id! %>
  secret_access_key: <%= Rails.application.env_credentials.cloudflare.r2.secret_access_key! %>
  endpoint: https://<%= Rails.application.env_credentials.cloudflare.account_id! %>.r2.cloudflarestorage.com
  bucket: <%= Rails.application.env_credentials.cloudflare.r2.bucket %>
  region: auto
  force_path_style: true
