name: Deploy
concurrency: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: hatchboxio/github-hatchbox-deploy-action@v2
        with:
          deploy_key: ${{ secrets.HATCHBOX_DEPLOY_KEY }}
